apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-eks-ml-cluster
  region: ap-northeast-1

privateCluster:
  enabled: true

nodeGroups:
  - name: ng-1
    instanceType: m3.large
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
